### ISSUE TITLE
MM not display Kalliope

### ISSUE THREAD

**Issue by bhalee** [kalliope-project/MMM-kalliope#2]
Hello,
I would like use for my kalliope the magic mirror project. The MM is freshly installed. The MMM-kalliope-master folder is in the modules folder. The module added to config.js.
The magic mirror neuron installed to my starter-kit kalliope. The yml file in my brains folder and added to my brain.yml. on_start_speaking : "mm-say" line ready in settings

Kallipe run without problem and MM as well but MM not display kalliope.

**Comment by Sispheor** [comment]
The name of the folder must be MMM-kalliope and not MMM-kalliope-master

**Comment by bhalee** [comment]
Thank you! Its working now :)
