### ISSUE TITLE
trouble

### ISSUE THREAD

**Issue by seramik** [kalliope-project/MMM-kalliope#3]
bonjour
j'ai un leger souci avec ce module
j'essaye de relier kalliope à mon magic mirror an suivant cette démarche :
https://www.framboise314.fr/magic-mirror/#Bonus_relier_Magic_Mirror_a_Kalliope
je clone ce module , ça me crée un dossier MMM-kalliope, RAS
ensuite je tente le " npm install" lancé de /magicmirror/modules/MMM-kalliope/
et c'est là que ça merdouille :

**Comment by Sispheor** [comment]
Hi @seramik .
Please no issue in other language than English. Thanks.

**Comment by seramik** [comment]
sorry ,
my trouble is here
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN modules No description
npm WARN modules No repository field.
npm WARN modules No README data
npm WARN modules No license field.

audited 1 package in 1.643s
found 0 vulnerabilities

**Comment by Sispheor** [comment]
* type `npm cache clean` and hit Enter
* type `sudo npm install -g npm` and hit Enter.
* Retry `npm install` and hit Enter.

**Comment by seramik** [comment]
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-03-01T18_39_56_837Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ sudo npm install -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.8.0
added 54 packages from 9 contributors, removed 15 packages and updated 44 packages in 34.362s
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN modules No description
npm WARN modules No repository field.
npm WARN modules No README data
npm WARN modules No license field.

audited 1 package in 1.608s
found 0 vulnerabilities





thanks for your rapidity

**Comment by Sispheor** [comment]
`npm cache clean --force`

**Comment by seramik** [comment]
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $

**Comment by Sispheor** [comment]
Yes..; and then the other commands I gave you...

**Comment by seramik** [comment]
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-03-01T18_55_39_059Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-03-01T18_59_47_630Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ sudo npm install -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.8.0
updated 1 package in 28.361s
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN modules No description
npm WARN modules No repository field.
npm WARN modules No README data
npm WARN modules No license field.

audited 1 package in 1.086s
found 0 vulnerabilities

pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $

**Comment by seramik** [comment]
it seems no change  ?

**Comment by Sispheor** [comment]
omg.... You were supposed to run the other commands.
OK:
* npm cache clean --force.
* `sudo npm install -g npm`
* npm install

**Comment by seramik** [comment]
sorry, i began with rasbian

pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ sudo npm install -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.8.0
updated 1 package in 26.709s
pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $ npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN modules No description
npm WARN modules No repository field.
npm WARN modules No README data
npm WARN modules No license field.

audited 1 package in 0.955s
found 0 vulnerabilities

pi@raspberrypi:~/MagicMirror/modules/MMM-kalliope $

**Comment by Sispheor** [comment]
Ok I don't know, sorry.
Try to do the install from the beginning.

**Comment by seramik** [comment]
ok TY
