### ISSUE TITLE
clone repo

### ISSUE THREAD

**Issue by haymaan** [kalliope-project/MMM-kalliope#4]
hello,
i've just install Kalliope,and know i want to clone it to my magicmirror what should i clone

"Clone this repo into ~/MagicMirror/modules directory."""

or just need to config Js

Configure your ~/MagicMirror/config/config.js:

thanks

**Comment by Sispheor** [comment]
You install the module like other community modules once Magic Mirror is installed.
Then you configure it into your config.js like described in the readme.

**Comment by haymaan** [comment]
Thanks for fast reply,but what should I clone ?? After full kalliope installation!!
I've installed it (kalliope)separately

**Comment by Sispheor** [comment]
After installing kalliope you need to install the kalliope magic mirror neuron
After installing Magic Mirror you need to install the Kalliope module.

**Comment by haymaan** [comment]
Okeeey neuron I've found, can you text me the module text please

**Comment by Sispheor** [comment]
The module kalliope text? What?

**Comment by haymaan** [comment]
Okey after full installing kalliope and than the neuron module, what should I do more the kalliope module what should I type git clone (!!!!) To get the kalliope module

**Comment by Sispheor** [comment]
Your English is awful, dude :)

It is explained in the doc. 
Clone this repo into `~/MagicMirror/modules` directory.
What do you don't understand here?

**Comment by haymaan** [comment]
Okey thanks forget about it I'll look for other module ,and remove kalliope.
