### ISSUE TITLE
Kalliope log files all gone

### ISSUE THREAD

**Issue by Dimasua** [kalliope-project/MMM-kalliope#9]
Hej, after I installed several MM modules Kalliope fails to start at boot, and log files are gone. 
When I created the again using the below commands, they are created, but after reboot gone again. 

sudo touch /var/log/kalliope.log
sudo touch /var/log/kalliope.err.log
sudo chown pi:pi /var/log/kalliope*

Can you please advise what to check to understand what creates that issue? Thank you in advance.

**Comment by Sispheor** [comment]
No idea.
It's not related to kalliope. 
Seems to be related to your env. Maybe not enot space. Or the rpi is out of resources. Maybe the /var is mounted on a temp filesystem. There is multiple possible reason for this kind of behavior.
But kalliope is not the main cause I think. You can try to get some help from the community on gitter chat.
